<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.boylu</groupId>
    <artifactId>blog</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>boylu-commom</module>
        <module>boylu-admin</module>
        <module>boylu-api</module>
        <module>boylu-server</module>
        <module>boylu-file</module>
        <module>boylu-quartz</module>
        <module>boylu-auth</module>
    </modules>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.0</version>
    </parent>

    <properties>
        <java.version>1.8</java.version>
        <mybatis-plus.version>3.5.2</mybatis-plus.version>
        <sa-token.version>1.39.0</sa-token.version>
        <package.version>1.0-SNAPSHOT</package.version>
    </properties>


    <build>
        <!-- 娉細maven榛樿鏄笉缂栬瘧锛屽洜姝ゅ姞涓婂涓媟esources鎵嶄細鐢熶骇瀵瑰簲鐨剎ml鏂囦欢 鐩殑锛氳В鍐砿ybatis鏄犲皠鍏崇郴涓嶅搴旈棶棰? start =============== -->
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
                <filtering>false</filtering>
            </testResource>
        </testResources>
        <!-- 娉細maven榛樿鏄笉缂栬瘧锛屽洜姝ゅ姞涓婂涓媟esources鎵嶄細鐢熶骇瀵瑰簲鐨剎ml鏂囦欢 鐩殑锛氳В鍐砿ybatis鏄犲皠鍏崇郴涓嶅搴旈棶棰? end =============== -->

        <plugins>
            <!-- maven鎵撳寘鎻掍欢 -> 灏嗘暣涓伐绋嬫墦鎴愪竴涓?fatjar -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <!-- 浣滅敤:椤圭洰鎵撴垚jar锛屽悓鏃舵妸鏈湴jar鍖呬篃寮曞叆杩涘幓 -->
                <configuration>
                    <includeSystemScope>true</includeSystemScope>
                    <mainClass>com.boylu.NeatAdminApplication</mainClass>
                </configuration>
            </plugin>
            <!--娣诲姞閰嶇疆璺宠繃娴嬭瘯-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>
        </plugins>

        <!-- 鍥哄畾Jar鍖呭悕瀛?-->
        <finalName>boylu-blog</finalName>
    </build>
</project> 