CREATE TABLE IF NOT EXISTS notion_article_sync_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  article_id BIGINT NULL,
  article_title VARCHAR(180) NULL,
  source_url VARCHAR(500) NULL,
  action VARCHAR(32) NOT NULL DEFAULT 'sync',
  status VARCHAR(32) NOT NULL DEFAULT 'running',
  image_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  imported_blocks INT NULL DEFAULT 0,
  changed_fields INT NULL DEFAULT 0,
  total_images INT NULL DEFAULT 0,
  localized_images INT NULL DEFAULT 0,
  failed_images INT NULL DEFAULT 0,
  message VARCHAR(500) NULL,
  warnings TEXT NULL,
  error_detail TEXT NULL,
  create_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_notion_sync_article_id (article_id),
  KEY idx_notion_sync_status (status),
  KEY idx_notion_sync_image_status (image_status),
  KEY idx_notion_sync_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
